-- ============================================================
-- hazemhassine.space — Supabase CMS
-- Paste this entire file into Supabase > SQL Editor > New query,
-- then click Run. The script is safe to run more than once.
-- ============================================================

create extension if not exists pgcrypto;

-- Private working documents. The browser never queries this table directly;
-- authenticated admin route handlers use the server-side service role.
create table if not exists public.cms_entries (
  key text primary key check (key ~ '^[a-zA-Z][a-zA-Z0-9_-]{1,79}$'),
  label text not null,
  section text not null default 'custom',
  description text not null default '',
  content_type text not null default 'object',
  draft_content jsonb not null default '{}'::jsonb,
  published_content jsonb,
  version integer not null default 1 check (version > 0),
  sort_order integer not null default 999,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

create table if not exists public.cms_revisions (
  id bigint generated by default as identity primary key,
  entry_key text not null references public.cms_entries(key) on delete cascade,
  version integer not null,
  content jsonb not null,
  change_type text not null default 'draft' check (change_type in ('draft', 'publish', 'restore')),
  created_at timestamptz not null default now()
);

create index if not exists cms_revisions_entry_created_idx
  on public.cms_revisions (entry_key, created_at desc);

-- Only this projection is exposed to visitors. It contains no draft column.
create table if not exists public.cms_published (
  key text primary key,
  content jsonb not null,
  version integer not null,
  published_at timestamptz not null default now()
);

create or replace function public.cms_prepare_entry_update()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  if new.draft_content is distinct from old.draft_content then
    new.version = old.version + 1;
  end if;
  return new;
end;
$$;

drop trigger if exists cms_prepare_entry_update_trigger on public.cms_entries;
create trigger cms_prepare_entry_update_trigger
before update on public.cms_entries
for each row execute function public.cms_prepare_entry_update();

create or replace function public.cms_record_draft_revision()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op = 'INSERT' or new.draft_content is distinct from old.draft_content then
    insert into public.cms_revisions (entry_key, version, content, change_type)
    values (new.key, new.version, new.draft_content, 'draft');
  end if;
  return new;
end;
$$;

drop trigger if exists cms_record_draft_revision_trigger on public.cms_entries;
create trigger cms_record_draft_revision_trigger
after insert or update on public.cms_entries
for each row execute function public.cms_record_draft_revision();

-- Atomically copies a private draft into the public read model.
create or replace function public.cms_publish_entry(p_key text)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_entry public.cms_entries%rowtype;
begin
  select * into current_entry
  from public.cms_entries
  where key = p_key
  for update;

  if not found then
    raise exception 'CMS entry % does not exist', p_key;
  end if;

  update public.cms_entries
  set published_content = current_entry.draft_content,
      published_at = now()
  where key = p_key;

  insert into public.cms_published (key, content, version, published_at)
  values (p_key, current_entry.draft_content, current_entry.version, now())
  on conflict (key) do update
    set content = excluded.content,
        version = excluded.version,
        published_at = excluded.published_at;

  insert into public.cms_revisions (entry_key, version, content, change_type)
  values (p_key, current_entry.version, current_entry.draft_content, 'publish');
end;
$$;

create or replace function public.cms_restore_revision(p_key text, p_revision_id bigint)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  restored_content jsonb;
begin
  select content into restored_content
  from public.cms_revisions
  where id = p_revision_id and entry_key = p_key;

  if restored_content is null then
    raise exception 'Revision % for CMS entry % does not exist', p_revision_id, p_key;
  end if;

  update public.cms_entries
  set draft_content = restored_content
  where key = p_key;

  if not found then
    raise exception 'CMS entry % does not exist', p_key;
  end if;
end;
$$;

revoke all on function public.cms_publish_entry(text) from public, anon, authenticated;
revoke all on function public.cms_restore_revision(text, bigint) from public, anon, authenticated;
grant execute on function public.cms_publish_entry(text) to service_role;
grant execute on function public.cms_restore_revision(text, bigint) to service_role;

alter table public.cms_entries enable row level security;
alter table public.cms_revisions enable row level security;
alter table public.cms_published enable row level security;

drop policy if exists "Public can read published CMS content" on public.cms_published;
create policy "Public can read published CMS content"
on public.cms_published for select
to anon, authenticated
using (true);

revoke all on public.cms_entries from anon, authenticated;
revoke all on public.cms_revisions from anon, authenticated;
grant select on public.cms_published to anon, authenticated;

-- Blog posts. Existing installations are upgraded in place.
create table if not exists public.posts (
  id text primary key,
  slug text not null unique,
  title text not null,
  date text not null,
  read_time text,
  excerpt text not null default '',
  content text not null default '',
  status text not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz
);

alter table public.posts add column if not exists status text not null default 'published';
alter table public.posts add column if not exists published_at timestamptz;
update public.posts set status = 'published' where status is null;

alter table public.posts enable row level security;
-- Remove legacy read policies from the previous instant-blog setup. Keeping an
-- old `using (true)` policy would accidentally expose newly-created drafts.
do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'posts'
      and cmd in ('SELECT', 'ALL')
  loop
    execute format('drop policy if exists %I on public.posts', existing_policy.policyname);
  end loop;
end;
$$;

create policy "Public can read published posts"
on public.posts for select
to anon, authenticated
using (status = 'published');
grant select on public.posts to anon, authenticated;

-- Durable contact inbox. There is intentionally no public policy; only the
-- service-role API can insert or read messages.
create table if not exists public.contact_messages (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(name) between 1 and 120),
  email text not null check (char_length(email) between 3 and 254),
  message text not null check (char_length(message) between 1 and 5000),
  status text not null default 'new' check (status in ('new', 'read', 'archived')),
  created_at timestamptz not null default now()
);

create index if not exists contact_messages_status_created_idx
  on public.contact_messages (status, created_at desc);

alter table public.contact_messages enable row level security;
revoke all on public.contact_messages from anon, authenticated;

-- Public asset buckets. Writes and deletes still go through protected admin
-- endpoints using the service role.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'cms-media',
  'cms-media',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml', 'application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'blog-images',
  'blog-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/svg+xml']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Public can view CMS media" on storage.objects;
create policy "Public can view CMS media"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'cms-media');

drop policy if exists "Public can view blog images" on storage.objects;
create policy "Public can view blog images"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'blog-images');

-- The admin's "Publish everything" action performs the initial content seed
-- from the repository defaults, so this migration remains readable and can be
-- reused across development, staging, and production projects.

notify pgrst, 'reload schema';
