// ============================================================
// Detailed Skills & Provenance Data
// Connects competencies with concrete work, research, and projects
// ============================================================

export const skillCategories = [
  { id: "all", label: "ALL" },
  { id: "ai", label: "AGENTIC AI & ML" },
  { id: "backend", label: "BACKEND & SYSTEMS" },
  { id: "frontend", label: "FRONTEND & UX" },
  { id: "data", label: "DATA & ANALYTICS" },
];

export const skillsWithProvenance = [
  {
    id: "langgraph",
    name: "LangGraph & Agents",
    shortName: "LangGraph",
    category: "ai",
    categoryLabel: "Agentic AI & ML",
    tag: "CORE FOCUS",
    tagType: "primary", // primary, warning, info, default
    icon: "hub",
    summary: "Orchestrating stateful, multi-step agent workflows with cyclic reasoning, bounded human-in-the-loop controls, and durable checkpointing.",
    provenance: [
      {
        entity: "Arbiter",
        role: "Dev Environment Control Plane",
        type: "project",
        badge: "PROJECT",
        summary: "Engineered autonomous agent interfaces with typed rollback operations and live container topology inspection.",
        link: "https://github.com/HazemHassine/Arbiter",
      },
      {
        entity: "Forma",
        role: "Job Application Workspace",
        type: "project",
        badge: "PROJECT",
        summary: "Designed bounded LangGraph workflows for multi-step résumé tailoring, company research, and cover-letter generation.",
        link: "https://github.com/HazemHassine/Forma",
      },
    ],
    ecosystem: ["LangGraph", "Python", "Tool Calling", "State Machines", "Gemini API"],
  },
  {
    id: "pytorch",
    name: "PyTorch & Deep Learning",
    shortName: "PyTorch",
    category: "ai",
    categoryLabel: "Agentic AI & ML",
    tag: "RESEARCH ML",
    tagType: "info",
    icon: "psychology",
    summary: "Designing, training, and benchmarking deep neural networks in privacy-preserving, federated, and multimodal environments.",
    provenance: [
      {
        entity: "BASIRA / Imperial College London",
        role: "ML Researcher Intern",
        type: "work",
        badge: "RESEARCH",
        summary: "Collaborated on FedLIMIT, developing PyTorch deep-learning models in federated environments for privacy-preserving medical image classification.",
        link: "#experience",
      },
      {
        entity: "Bielefeld University",
        role: "M.Sc. Intelligent Interactive Systems",
        type: "education",
        badge: "ACADEMIA",
        summary: "Graduate research and coursework in deep learning, reinforcement learning, and autonomous interactive agents.",
        link: "#education",
      },
    ],
    ecosystem: ["PyTorch", "Federated Learning", "Computer Vision", "Scikit-Learn"],
  },
  {
    id: "mcp",
    name: "Model Context Protocol (MCP)",
    shortName: "MCP Tooling",
    category: "ai",
    categoryLabel: "Agentic AI & ML",
    tag: "AGENT PROTOCOL",
    tagType: "primary",
    icon: "memory",
    summary: "Standardizing tool exposure, deterministic code navigation, and semantic context retrieval for coding LLMs and developer sidecars.",
    provenance: [
      {
        entity: "Gemini-MCP",
        role: "Repository Intelligence Server",
        type: "project",
        badge: "PROJECT",
        summary: "Exposes AST-based code navigation, LanceDB semantic vector search, and local SQLite history as tools to coding agents.",
        link: "https://github.com/HazemHassine/Gemini-Mcp",
      },
    ],
    ecosystem: ["MCP Protocol", "LanceDB", "SQLite", "AST Navigation", "Python"],
  },
  {
    id: "python",
    name: "Python (Async / FastAPI / Core)",
    shortName: "Python",
    category: "backend",
    categoryLabel: "Backend & Systems",
    tag: "DAILY DRIVER",
    tagType: "primary",
    icon: "terminal",
    summary: "High-performance asynchronous backends, analytical pipelines, data processing engines, and machine learning infrastructure.",
    provenance: [
      {
        entity: "Siemens",
        role: "UX Data Analyst",
        type: "work",
        badge: "WORK",
        summary: "Engineered Python analytical pipelines reconstructing user journeys and clustering behavioral funnels across 400K+ sessions.",
        link: "#experience",
      },
      {
        entity: "Arbiter & Forma & RepoTrajectory",
        role: "Core Backend Engine",
        type: "project",
        badge: "PROJECT",
        summary: "Built async FastAPI services with robust Pydantic schemas, WebSocket streaming, and background task queues.",
        link: "https://github.com/HazemHassine/Arbiter",
      },
      {
        entity: "ISIE",
        role: "Information System Specialist",
        type: "work",
        badge: "WORK",
        summary: "Automated repetitive institutional data-processing tasks and maintained core internal systems.",
        link: "#experience",
      },
    ],
    ecosystem: ["FastAPI", "Pydantic", "Pandas", "Uvicorn", "Pytest", "NumPy"],
  },
  {
    id: "fastapi",
    name: "FastAPI & Async RPC",
    shortName: "FastAPI",
    category: "backend",
    categoryLabel: "Backend & Systems",
    tag: "PROD BACKEND",
    tagType: "primary",
    icon: "bolt",
    summary: "Building lightweight, type-safe API gateways, real-time WebSocket event streaming, and agent control planes.",
    provenance: [
      {
        entity: "Arbiter",
        role: "Control Plane Gateway",
        type: "project",
        badge: "PROJECT",
        summary: "REST & WebSocket endpoints coordinating container lifecycles, port proxies, and state rollbacks.",
        link: "https://github.com/HazemHassine/Arbiter",
      },
      {
        entity: "RepoTrajectory",
        role: "Analytics Backend",
        type: "project",
        badge: "PROJECT",
        summary: "Durable background collection jobs and GitHub REST scoring pipelines.",
        link: "https://github.com/HazemHassine/github_analysis",
      },
    ],
    ecosystem: ["FastAPI", "WebSockets", "Asyncio", "Pydantic V2", "CORS"],
  },
  {
    id: "nextjs",
    name: "Next.js, React & TypeScript",
    shortName: "Next.js / React",
    category: "frontend",
    categoryLabel: "Frontend & UX",
    tag: "FULL STACK UI",
    tagType: "primary",
    icon: "data_object",
    summary: "Modern App Router architectures, server components, reactive state management, and high-performance interactive interfaces.",
    provenance: [
      {
        entity: "Portfolio & Arbiter Dashboard",
        role: "Frontend Architect",
        type: "project",
        badge: "PROJECT",
        summary: "Engineered custom brutalist UI, live terminal controls, 3D Canvas integration, and fluid layout transitions.",
        link: "https://github.com/HazemHassine/Arbiter",
      },
      {
        entity: "Make It Happen",
        role: "Web Developer Intern",
        type: "work",
        badge: "WORK",
        summary: "Developed React components and improved JavaScript frontend performance for responsive e-commerce.",
        link: "#experience",
      },
    ],
    ecosystem: ["Next.js (App Router)", "React 19", "TypeScript", "TailwindCSS", "Three.js"],
  },
  {
    id: "docker",
    name: "Docker & Container Topologies",
    shortName: "Docker",
    category: "backend",
    categoryLabel: "Backend & Systems",
    tag: "INFRASTRUCTURE",
    tagType: "info",
    icon: "view_in_ar",
    summary: "Containerization, isolated local runtime orchestration, and multi-service development topologies.",
    provenance: [
      {
        entity: "Arbiter",
        role: "Container Orchestration",
        type: "project",
        badge: "PROJECT",
        summary: "Live container discovery, environment inspection, port collision detection, and sandboxed runtimes.",
        link: "https://github.com/HazemHassine/Arbiter",
      },
      {
        entity: "Siemens",
        role: "Industrial AI Inference Server",
        type: "work",
        badge: "WORK",
        summary: "Telemetry analysis and workflow benchmarking on containerized industrial AI inference servers.",
        link: "#experience",
      },
    ],
    ecosystem: ["Docker", "Docker Compose", "Linux / Bash", "Networking"],
  },
  {
    id: "databases",
    name: "PostgreSQL, SQLite & Vector DBs",
    shortName: "Databases & Vector",
    category: "backend",
    categoryLabel: "Backend & Systems",
    tag: "DATA PERSISTENCE",
    tagType: "info",
    icon: "database",
    summary: "Relational schemas, local-first embedded databases (SQLite/LanceDB), and historical telemetry persistence.",
    provenance: [
      {
        entity: "RepoTrajectory & OSS Maintainer",
        role: "Data Persistence",
        type: "project",
        badge: "PROJECT",
        summary: "Historical CI run preservation, relational scoring tables, and audit logs in PostgreSQL.",
        link: "https://github.com/HazemHassine/github_analysis",
      },
      {
        entity: "Gemini-MCP",
        role: "Vector & Semantic Storage",
        type: "project",
        badge: "PROJECT",
        summary: "LanceDB embedded vector index for fast semantic repository querying.",
        link: "https://github.com/HazemHassine/Gemini-Mcp",
      },
    ],
    ecosystem: ["PostgreSQL", "SQLite", "LanceDB", "SQLAlchemy", "Alembic"],
  },
  {
    id: "data_analytics",
    name: "Data Analytics & Clustering",
    shortName: "Analytics & BI",
    category: "data",
    categoryLabel: "Data & Analytics",
    tag: "ENTERPRISE PROD",
    tagType: "primary",
    icon: "analytics",
    summary: "Large-scale telemetry analysis, behavioral clustering, funnel reconstruction, and explainable scoring metrics.",
    provenance: [
      {
        entity: "Siemens",
        role: "UX Data Analyst (Working Student)",
        type: "work",
        badge: "WORK",
        summary: "Analyzed 400,000+ user sessions for Insights Hub Monitor; uncovered behavioral friction clusters to guide product roadmap.",
        link: "#experience",
      },
      {
        entity: "RepoTrajectory",
        role: "OSS Health Scoring",
        type: "project",
        badge: "PROJECT",
        summary: "Built explainable scoring models aggregating GitHub metrics, issue velocities, and contributor retention.",
        link: "https://github.com/HazemHassine/github_analysis",
      },
    ],
    ecosystem: ["Pandas", "NumPy", "Jupyter", "Scikit-Learn", "Data Viz"],
  },
];
