// ============================================================================
// PORTFOLIO CONTEXT VAULT: ATOMIZED KNOWLEDGE CARDS
// Structured according to the 6 verified categories from Forma's Context Vault:
// - profile_persona: Engineering ethos, systems principles, positioning
// - experience_project: Specific projects, architectures, systems built
// - achievement_metric: Verifiable numbers, scale, performance benchmarks
// - skills_arsenal: Concrete technologies and practical implementations
// - education_credential: Degrees, academic focus, specialized research
// - proof_link: Repositories, live showcases, publications, verifiable proof
// ============================================================================

export const VAULT_CATEGORIES = {
  profile_persona: {
    id: 'profile_persona',
    label: 'Persona & Ethos',
    color: '#ffffff',
    threeColor: 0xffffff,
  },
  experience_project: {
    id: 'experience_project',
    label: 'Projects & Systems',
    color: '#00f0ff',
    threeColor: 0x00f0ff,
  },
  achievement_metric: {
    id: 'achievement_metric',
    label: 'Metrics & Scale',
    color: '#00ff9d',
    threeColor: 0x00ff9d,
  },
  skills_arsenal: {
    id: 'skills_arsenal',
    label: 'Tech Arsenal',
    color: '#ffb74d',
    threeColor: 0xffb74d,
  },
  education_credential: {
    id: 'education_credential',
    label: 'Education & Research',
    color: '#b388ff',
    threeColor: 0xb388ff,
  },
  proof_link: {
    id: 'proof_link',
    label: 'Verified Links',
    color: '#ff4081',
    threeColor: 0xff4081,
  },
};

export const VAULT_CARDS = [
  // --------------------------------------------------------------------------
  // 1. PERSONA & ETHOS
  // --------------------------------------------------------------------------
  {
    id: 'persona-local-first',
    category: 'profile_persona',
    entity: 'Engineering Philosophy',
    title: 'Local-First Architecture & Privacy by Default',
    content: 'Prioritizes local compute, transparent data boundaries, and zero unconsented telemetry. Projects like Arbiter and Forma enforce strict local state isolation with SQLite backups and scoped filesystem sandboxes.',
    metrics: ['100% local-first storage option', 'Zero unconsented cloud telemetry'],
    tags: ['philosophy', 'local-first', 'privacy', 'sqlite', 'sandboxing'],
    relatedNodeIds: ['proj-arbiter', 'proj-forma', 'exp-basira'],
    cluster: 'systems_ethos',
    showcaseUrl: null,
  },
  {
    id: 'persona-human-in-loop',
    category: 'profile_persona',
    entity: 'AI Design Philosophy',
    title: 'Bounded Agentic Workflows & Human-in-the-Loop',
    content: 'Rejects black-box unconstrained autonomous agent loops in favor of step-bounded, typed-operation workflows with human approval checkpoints, compensating transactions, and auditability.',
    metrics: ['Strict 5-tier risk matrix', 'Approval-gated state mutations'],
    tags: ['ai-agents', 'langgraph', 'human-in-the-loop', 'safety', 'orchestration'],
    relatedNodeIds: ['proj-arbiter', 'proj-forma', 'skill-langgraph'],
    cluster: 'systems_ethos',
    showcaseUrl: null,
  },

  // --------------------------------------------------------------------------
  // 2. PROJECTS & SYSTEMS
  // --------------------------------------------------------------------------
  {
    id: 'proj-arbiter',
    category: 'experience_project',
    entity: 'Arbiter',
    title: 'Arbiter: Local-First SRE Dev Environment Control Plane',
    content: 'Linux operations control plane that gathers socket evidence via ss and /proc, maps Docker Compose services, deterministically calculates collision-free replacement ports, and rewrites YAML with atomic rollbacks.',
    metrics: ['Sub-15ms rollback capability', '5-tier persisted approval matrix', 'Deterministic port allocator'],
    tags: ['python', 'fastapi', 'docker', 'langgraph', 'sre', 'ast-rewrite', 'sqlite'],
    relatedNodeIds: ['metric-arbiter-risk', 'skill-docker', 'skill-python', 'skill-langgraph', 'persona-local-first'],
    cluster: 'agentic_systems',
    showcaseUrl: '/projects/arbiter',
    githubUrl: 'https://github.com/HazemHassine/Arbiter',
  },
  {
    id: 'proj-forma',
    category: 'experience_project',
    entity: 'Forma',
    title: 'Forma: Agentic Job Application & Context Vault Platform',
    content: 'Multi-step LangGraph agentic workspace pairing web-grounded company research with candidate context distillation, section-by-section CV versioning, and human-guided cover letter synthesis.',
    metrics: ['6-category verified context extraction', 'Source-backed research with confidence scores'],
    tags: ['python', 'fastapi', 'react', 'langgraph', 'context-vault', 'rag', 'gemini'],
    relatedNodeIds: ['metric-forma-vault', 'skill-langgraph', 'skill-react', 'persona-human-in-loop', 'proj-arbiter'],
    cluster: 'agentic_systems',
    showcaseUrl: '/projects/forma',
    githubUrl: 'https://github.com/HazemHassine/Forma',
  },
  {
    id: 'proj-repotrajectory',
    category: 'experience_project',
    entity: 'RepoTrajectory',
    title: 'RepoTrajectory: Open-Source Repository Trajectory Analyzer',
    content: 'Deep Git commit velocity, contributor churn, and organizational dependency topology analyzer. Computes bus factors and trajectory forecasts across multi-year repository histories.',
    metrics: ['Full commit graph traversal', 'Sub-second AST parsing of repo histories'],
    tags: ['git', 'python', 'analytics', 'data-visualization', 'open-source'],
    relatedNodeIds: ['skill-python', 'skill-data-pipelines', 'proj-gitaudit', 'exp-siemens'],
    cluster: 'devtools_analytics',
    showcaseUrl: '/projects/repotrajectory',
    githubUrl: 'https://github.com/HazemHassine/RepoTrajectory',
  },
  {
    id: 'proj-gitaudit',
    category: 'experience_project',
    entity: 'GitAudit',
    title: 'GitAudit: Automated Repository Security & Drift Auditor',
    content: 'Static analysis and security audit engine scanning Git trees for leaked entropy, outdated dependency vectors, permission creep, and unverified CI/CD workflow executions.',
    metrics: ['Regex + entropy credential detection', 'Zero false-positive secret triage'],
    tags: ['security', 'python', 'git', 'cli', 'audit'],
    relatedNodeIds: ['proj-repotrajectory', 'skill-python', 'skill-docker'],
    cluster: 'devtools_analytics',
    showcaseUrl: '/projects/gitaudit',
    githubUrl: 'https://github.com/HazemHassine/GitAudit',
  },
  {
    id: 'proj-gemini-mcp',
    category: 'experience_project',
    entity: 'Gemini-MCP',
    title: 'Gemini-MCP: Anthropic Model Context Protocol Server for Gemini',
    content: 'Production stdio/SSE Model Context Protocol (MCP) server exposing Google Gemini models, structured multimodal tooling, and filesystem memory bridges to AI agent ecosystems.',
    metrics: ['Full MCP specification compliance', 'Sub-50ms tool negotiation latency'],
    tags: ['mcp', 'gemini', 'typescript', 'node', 'ai-tooling', 'protocols'],
    relatedNodeIds: ['skill-gemini', 'skill-mcp', 'proj-arbiter'],
    cluster: 'agentic_systems',
    showcaseUrl: '/projects/gemini-mcp',
    githubUrl: 'https://github.com/HazemHassine/gemini-mcp-server',
  },
  {
    id: 'proj-rsvp-shift',
    category: 'experience_project',
    entity: 'RSVP-Shift',
    title: 'RSVP-Shift: Asynchronous Event & Shift Coordination Engine',
    content: 'High-concurrency full-stack scheduling and volunteer shift management platform with real-time websocket updates, automated reminder triggers, and transactional conflict resolution.',
    metrics: ['Sub-second slot reconciliation', 'Fault-tolerant message dispatch'],
    tags: ['typescript', 'react', 'websockets', 'postgresql', 'scheduling'],
    relatedNodeIds: ['skill-react', 'skill-typescript', 'skill-docker'],
    cluster: 'devtools_analytics',
    showcaseUrl: '/projects/rsvp-shift',
    githubUrl: 'https://github.com/HazemHassine/RSVP-Shift',
  },

  // --------------------------------------------------------------------------
  // 3. WORK & RESEARCH EXPERIENCES
  // --------------------------------------------------------------------------
  {
    id: 'exp-siemens',
    category: 'experience_project',
    entity: 'Siemens',
    title: 'Siemens: Working Student User Journey & Session Analytics',
    content: 'Engineered analytics and telemetry pipelines for Siemens Insights Hub Monitor and Industrial AI Inference Server in Erlangen, Germany. Reconstructed 400,000+ industrial user sessions and identified behavioral friction clusters.',
    metrics: ['400K+ user sessions analyzed', 'High-throughput Python analytical pipelines'],
    tags: ['siemens', 'industrial-ai', 'telemetry', 'python', 'session-analysis', 'clustering'],
    relatedNodeIds: ['metric-siemens-400k', 'skill-python', 'skill-data-pipelines', 'edu-bielefeld'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'exp-basira',
    category: 'experience_project',
    entity: 'Basira / Imperial College London',
    title: 'Basira / Imperial College: Federated Learning & Privacy ML Researcher',
    content: 'Conducted cutting-edge research on the FedLIMIT project focused on privacy-preserving collaborative learning. Developed PyTorch deep-learning models in federated, non-IID environments for medical image classification with differential privacy guarantees.',
    metrics: ['Differential privacy guarantees', 'Non-IID convergence optimization in medical imaging'],
    tags: ['federated-learning', 'pytorch', 'deep-learning', 'privacy', 'medical-imaging', 'imperial-college'],
    relatedNodeIds: ['metric-basira-privacy', 'skill-pytorch', 'skill-deep-learning', 'edu-bielefeld'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'exp-isie',
    category: 'experience_project',
    entity: 'ISIE',
    title: 'ISIE: Information System Automation Specialist',
    content: 'Automated internal data processing pipelines and digital operations for election logistics in Tunisia. Designed automated ETL verification scripts and trained over 100 operational staff on new digital workflows.',
    metrics: ['100+ operational staff trained', '100% automated ETL validation on ingestion'],
    tags: ['automation', 'data-pipelines', 'etl', 'sql', 'system-admin'],
    relatedNodeIds: ['metric-isie-staff', 'skill-data-pipelines', 'edu-passau'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },

  // --------------------------------------------------------------------------
  // 4. ACHIEVEMENTS & SCALE METRICS
  // --------------------------------------------------------------------------
  {
    id: 'metric-siemens-400k',
    category: 'achievement_metric',
    entity: 'Siemens Telemetry',
    title: '400,000+ Industrial Sessions Reconstructed',
    content: 'Reconstructed and clustered over 400,000 distinct telemetry sessions across Insights Hub Monitor and Industrial AI Inference Server, identifying operational bottlenecks and friction pathways.',
    metrics: ['400,000+ sessions', 'Insights Hub Monitor', 'Industrial AI Inference Server'],
    tags: ['metrics', 'scale', 'siemens', 'telemetry', 'clustering'],
    relatedNodeIds: ['exp-siemens', 'skill-data-pipelines', 'skill-python'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'metric-basira-privacy',
    category: 'achievement_metric',
    entity: 'FedLIMIT / Basira',
    title: 'Privacy-Preserving Federated Deep Learning Convergence',
    content: 'Achieved robust model convergence across heterogeneous non-IID client distributions while enforcing strict differential privacy budgets for clinical medical image classification.',
    metrics: ['Non-IID convergence', 'Differential privacy guarantees', 'Multi-client federation'],
    tags: ['metrics', 'federated-learning', 'pytorch', 'privacy'],
    relatedNodeIds: ['exp-basira', 'skill-pytorch', 'skill-deep-learning'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'metric-arbiter-risk',
    category: 'achievement_metric',
    entity: 'Arbiter Control Plane',
    title: '5-Tier Risk Isolation Matrix & Rollback Guarantee',
    content: 'Categorized all OS-level mutating actions into a 5-tier persisted risk matrix with SQLite UUID logs and sub-15ms compensating rollback transactions on failed Docker Compose operations.',
    metrics: ['5-tier risk matrix', 'Sub-15ms rollback', '100% atomic configuration backup'],
    tags: ['metrics', 'sre', 'docker', 'safety', 'rollback'],
    relatedNodeIds: ['proj-arbiter', 'skill-docker', 'persona-human-in-loop'],
    cluster: 'agentic_systems',
    showcaseUrl: '/projects/arbiter',
  },
  {
    id: 'metric-forma-vault',
    category: 'achievement_metric',
    entity: 'Forma Context Vault',
    title: '6-Category Knowledge Distillation & Citation Grounding',
    content: 'Automated multi-source context distillation producing atomized knowledge cards with source-backed confidence scores and bounded prompt synthesis for zero-hallucination agent generation.',
    metrics: ['6 verified categories', '100% source-grounded LLM synthesis'],
    tags: ['metrics', 'rag', 'context-vault', 'gemini', 'langgraph'],
    relatedNodeIds: ['proj-forma', 'skill-langgraph', 'persona-local-first'],
    cluster: 'agentic_systems',
    showcaseUrl: '/projects/forma',
  },
  {
    id: 'metric-isie-staff',
    category: 'achievement_metric',
    entity: 'ISIE Pipeline Automation',
    title: '100+ Staff Onboarded & Automated ETL Pipelines',
    content: 'Trained and onboarded over 100 staff on newly digitized operational systems while implementing automated validation scripts that eliminated manual entry inconsistencies.',
    metrics: ['100+ staff onboarded', 'Zero ingestion discrepancy during election audits'],
    tags: ['metrics', 'training', 'automation', 'etl'],
    relatedNodeIds: ['exp-isie', 'skill-data-pipelines'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },

  // --------------------------------------------------------------------------
  // 5. TECHNICAL ARSENAL & CORE SKILLS
  // --------------------------------------------------------------------------
  {
    id: 'skill-langgraph',
    category: 'skills_arsenal',
    entity: 'LangGraph & Agent Orchestration',
    title: 'LangGraph, Multi-Agent Cycles & State Graphs',
    content: 'Architects cyclic state graphs, bounded tool loops, structured NDJSON operational streaming, and conditional routing using LangGraph and LangChain v1.',
    metrics: ['Multi-agent state machines', 'Bounded recursion depth guards'],
    tags: ['langgraph', 'langchain', 'agentic-ai', 'orchestration', 'python'],
    relatedNodeIds: ['proj-arbiter', 'proj-forma', 'persona-human-in-loop'],
    cluster: 'agentic_systems',
    showcaseUrl: null,
  },
  {
    id: 'skill-pytorch',
    category: 'skills_arsenal',
    entity: 'PyTorch & Deep Learning',
    title: 'PyTorch, Custom Tensors & Model Architectures',
    content: 'Implements convolutional and transformer architectures, federated optimization routines (FedAvg/FedProx), and loss penalization for heterogeneous data distributions.',
    metrics: ['Custom gradient optimization', 'Distributed tensor training'],
    tags: ['pytorch', 'deep-learning', 'python', 'machine-learning', 'gpu'],
    relatedNodeIds: ['exp-basira', 'metric-basira-privacy', 'edu-bielefeld'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'skill-docker',
    category: 'skills_arsenal',
    entity: 'Docker & Container Sandboxing',
    title: 'Docker SDK, Container Orchestration & Compose Rewriting',
    content: 'Controls container lifecycles programmatically via Docker SDK, inspects daemon socket events, validates Compose YAML ASTs, and isolates untrusted processes.',
    metrics: ['Programmatic socket inspection', 'AST Compose rewriting'],
    tags: ['docker', 'containers', 'devops', 'linux', 'orchestration'],
    relatedNodeIds: ['proj-arbiter', 'proj-gitaudit', 'metric-arbiter-risk'],
    cluster: 'devtools_analytics',
    showcaseUrl: null,
  },
  {
    id: 'skill-python',
    category: 'skills_arsenal',
    entity: 'Async Python & Systems Engineering',
    title: 'Async Python, FastAPI, Typer & Linux Systems',
    content: 'Builds high-performance asynchronous microservices, Linux /proc inspectors, AST analyzers, and robust CLI tooling using FastAPI, Typer, and Pydantic v2.',
    metrics: ['Async event loops', 'Sub-millisecond socket parsers'],
    tags: ['python', 'fastapi', 'typer', 'linux', 'async', 'pydantic'],
    relatedNodeIds: ['proj-arbiter', 'proj-repotrajectory', 'exp-siemens', 'skill-docker'],
    cluster: 'devtools_analytics',
    showcaseUrl: null,
  },
  {
    id: 'skill-react',
    category: 'skills_arsenal',
    entity: 'React 19 & Next.js App Router',
    title: 'React 19, Next.js App Router & Reactive Frontends',
    content: 'Builds responsive, accessible web architectures leveraging React 19 Server Components, streaming SSR, Framer Motion animations, and custom CSS design systems.',
    metrics: ['Zero hydration mismatch', 'Under 50ms interaction latency'],
    tags: ['react', 'nextjs', 'typescript', 'frontend', 'tailwind'],
    relatedNodeIds: ['proj-forma', 'proj-rsvp-shift', 'skill-threejs'],
    cluster: 'devtools_analytics',
    showcaseUrl: null,
  },
  {
    id: 'skill-threejs',
    category: 'skills_arsenal',
    entity: 'Three.js & WebGL Visualizations',
    title: 'Three.js, React Three Fiber & 3D Interactive Spaces',
    content: 'Engineers interactive 3D WebGL scenes, particle physics, custom vertex shaders, camera lerping, and raycasted spatial nodes for immersive web experiences.',
    metrics: ['60 FPS WebGL rendering', 'Custom shader materials'],
    tags: ['threejs', 'webgl', '3d', 'r3f', 'graphics'],
    relatedNodeIds: ['skill-react', 'proj-forma'],
    cluster: 'devtools_analytics',
    showcaseUrl: null,
  },
  {
    id: 'skill-data-pipelines',
    category: 'skills_arsenal',
    entity: 'Data Engineering & Telemetry Pipelines',
    title: 'High-Throughput Telemetry & Time-Series Data Pipelines',
    content: 'Designs ETL extraction pipelines, behavioral clustering models, and event-driven data streaming routines capable of processing millions of records reliably.',
    metrics: ['400K+ records batch processing', 'Fault-tolerant ingestion'],
    tags: ['data-engineering', 'etl', 'sql', 'telemetry', 'analytics'],
    relatedNodeIds: ['exp-siemens', 'exp-isie', 'metric-siemens-400k'],
    cluster: 'industrial_research',
    showcaseUrl: null,
  },
  {
    id: 'skill-gemini',
    category: 'skills_arsenal',
    entity: 'Google Gemini & Multimodal AI',
    title: 'Google Gemini 2.5/3.5, Structured Outputs & Tool Calling',
    content: 'Leverages Google Generative AI SDK for low-latency reasoning, structured JSON schema outputs, multi-turn tool calling, and multimodal embeddings.',
    metrics: ['Structured JSON enforcement', 'Real-time tool execution'],
    tags: ['gemini', 'google-ai', 'llm', 'embeddings', 'ai-sdk'],
    relatedNodeIds: ['proj-gemini-mcp', 'proj-forma', 'skill-mcp'],
    cluster: 'agentic_systems',
    showcaseUrl: null,
  },
  {
    id: 'skill-mcp',
    category: 'skills_arsenal',
    entity: 'Model Context Protocol (MCP)',
    title: 'Model Context Protocol: Tools, Resources & Prompts',
    content: 'Implements both client and server sides of the Anthropic Model Context Protocol, enabling interoperable agent-to-environment tool execution over stdio and SSE.',
    metrics: ['Stdio and SSE protocol support', 'Dynamic tool discovery'],
    tags: ['mcp', 'protocols', 'ai-agents', 'interoperability'],
    relatedNodeIds: ['proj-gemini-mcp', 'proj-arbiter', 'skill-gemini'],
    cluster: 'agentic_systems',
    showcaseUrl: null,
  },

  // --------------------------------------------------------------------------
  // 6. EDUCATION & ACADEMIC CREDENTIALS
  // --------------------------------------------------------------------------
  {
    id: 'edu-bielefeld',
    category: 'education_credential',
    entity: 'Bielefeld University',
    title: 'M.Sc. Intelligent Interactive Systems — Bielefeld University',
    content: 'Pursuing M.Sc. in Bielefeld, Germany (2025 - Present). Specializing in autonomous interactive agents, deep reinforcement learning, cognitive human-machine interaction, and scalable AI systems.',
    metrics: ['M.Sc. Candidate', 'Intelligent Interactive Systems', 'Germany'],
    tags: ['education', 'bielefeld', 'germany', 'msc', 'interactive-systems', 'ai'],
    relatedNodeIds: ['edu-passau', 'exp-siemens', 'exp-basira', 'skill-pytorch'],
    cluster: 'academic_foundations',
    showcaseUrl: null,
  },
  {
    id: 'edu-passau',
    category: 'education_credential',
    entity: 'University of Passau',
    title: 'M.Sc. Computer Science — University of Passau',
    content: 'Completed foundational Master coursework in Passau, Germany (2024 - 2025) covering intelligent technical systems, distributed databases, network architectures, and algorithms.',
    metrics: ['Distributed databases', 'Network architecture', 'Germany'],
    tags: ['education', 'passau', 'germany', 'distributed-systems', 'computer-science'],
    relatedNodeIds: ['edu-bielefeld', 'edu-isimm', 'exp-siemens'],
    cluster: 'academic_foundations',
    showcaseUrl: null,
  },
  {
    id: 'edu-isimm',
    category: 'education_credential',
    entity: 'ISIMM / University of Monastir',
    title: 'B.Sc. Software Engineering & Information Systems Architecture',
    content: 'Graduated in 2023 with a German-equivalent grade of 2.4. Core coursework in Big Data engineering, AI algorithms, software architectures, and database design.',
    metrics: ['German-equivalent grade: 2.4', 'Focus on Big Data & AI'],
    tags: ['education', 'isimm', 'monastir', 'software-engineering', 'bsc'],
    relatedNodeIds: ['edu-passau', 'exp-isie'],
    cluster: 'academic_foundations',
    showcaseUrl: null,
  },
];

export const VAULT_CLUSTERS = {
  agentic_systems: {
    id: 'agentic_systems',
    label: 'Agentic AI & Orchestration',
    center: [0, 1.8, 0],
    color: '#00f0ff',
  },
  industrial_research: {
    id: 'industrial_research',
    label: 'Industrial Telemetry & Research ML',
    center: [-4.0, -0.6, 1.8],
    color: '#b388ff',
  },
  devtools_analytics: {
    id: 'devtools_analytics',
    label: 'Developer Tools & SRE Platforms',
    center: [4.0, -0.6, -1.8],
    color: '#00ff9d',
  },
  academic_foundations: {
    id: 'academic_foundations',
    label: 'Academic & Theoretical Foundations',
    center: [0, -3.2, 2.2],
    color: '#ffb74d',
  },
  systems_ethos: {
    id: 'systems_ethos',
    label: 'Engineering Ethos & Safety',
    center: [0, 3.6, -1.8],
    color: '#ffffff',
  },
};
